[package]
name = "land-server"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
land-dao = { workspace = true }
land-helpers = { workspace = true }
tokio = { workspace = true }
