[package]
name = "land-edge"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
clap = { workspace = true }
land-core = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
