manifest = "v1"
name = "rust-hello-world"
template_name = "Hello World"
project = "rust-basic-example"
description = "Deliver a simple Hello World message to the browser."
authors = []
language = "rust"

[build]
rust_target_dir = "../../target"