[workspace]
members = [
    "crates/common",
    "crates/core",
    "crates/dao",
    "crates/sdk",
    "crates/sdk-macro",
    "crates/wasm",
    "crates/wasm-gen",
    "crates/worker-server",
    "land-cli",
    "land-server",
    "land-worker",
    "tests/rust-helloworld"
]
default-members = ["land-cli"]
resolver = "2"

[workspace.package]
version = "0.3.1"
edition = "2021"
authors = ["fuxiaohei <fudong0797@gmail.com>"]

[workspace.dependencies]
anyhow = "1.0.82"
async-trait = "0.1.80"
axum = "0.7.5"
base64 = "0.22.0"
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive", "env"] }
http = "1.1.0"
hostname = "0.4.0"
land-common = { path = "./crates/common" }
land-core = { path = "./crates/core" }
land-dao = { path = "./crates/dao" }
land-sdk = { path = "crates/sdk" }
land-sdk-macro = { path = "crates/sdk-macro" }
land-wasm = { path = "./crates/wasm" }
land-wasm-gen = { path = "./crates/wasm-gen" }
land-worker-server = { path = "./crates/worker-server" }
lazy_static = "1.4.0"
md5 = "0.7.0"
once_cell = "1.19.0"
opendal = { version = "0.45.1", default-features = false, features = [
    "services-fs",
    "services-s3",
    "services-memory",
    "rustls",
] }
rand = "0.8.5"
reqwest = { version = "0.12.4", default-features = false, features = [
    "stream",
    "rustls-tls",
    "json",
] }
rust-embed = { version = "8.3.0", features = [
    "include-exclude",
    "compression",
] }
serde = { version = "1.0.199", features = ["derive"] }
serde_json = "1.0.116"
serde_yaml = "0.9.33"
time = { version = "0.3.36", features = ["local-offset"] }
tokio = { version = "1.37.0", features = ["full"] }
tower-http = { version = "0.5.2", features = [
    "timeout",
    "cors",
    "fs",
    "trace",
] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [
    "time",
    "local-time",
    "env-filter",
] }
uuid = { version = "1.8.0", features = ["v4"] }
walkdir = "2.5.0"
wit-bindgen = "0.24.0"
wit-bindgen-core = "0.24.0"
wit-bindgen-rust = "0.24.0"
wit-component = "0.206.0"
