[package]
name = "moni-serverless"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[workspace]
members = ["moni-cli", "moni-core"]

[workspace.package]
version = "0.1.1"
edition = "2021"
authors = ["fuxiaohei <fudong0797@gmail.com>"]

[dependencies]

[workspace.dependencies]
clap = { version = "4.1.8", features = ["derive"] }
tokio = { version = "1.26.0", features = ["full"] }
serde = { version = "1.0.152", features = ["derive"] }
anyhow = "1.0.69"
bytes = "1.4.0"
http = "0.2.9"
bincode = "1.3.3"
toml = "0.7.2"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = [
    "time",
    "local-time",
    "env-filter"
] }
time = "0.3.20"
lazy_static = "1.4.0"
