[workspace.package]
version = "0.5.0-beta.18"
edition = "2021"
authors = ["fuxiaohei <fudong0797@gmail.com>"]

[workspace]
members = [
    "land-cli",
    "land-server",
    "land-worker",
    "lib/common",
    "lib/core",
    "lib/dao",
    "lib/sdk",
    "lib/sdk-macro",
    "lib/vars",
    "lib/wasm-gen",
    "lib/wasm-host",
    "lib/wasm-server",
    "tests/hello-wasm",
]
default-members = ["land-cli"]
resolver = "2"

[workspace.dependencies]
# internal dependencies
land-common = { path = "lib/common" }
land-core = { path = "lib/core" }
land-dao = { path = "lib/dao" }
land-vars = { path = "lib/vars" }
land-sdk-macro = { path = "lib/sdk-macro" }
land-wasm-gen = { path = "lib/wasm-gen" }
land-wasm-host = { path = "lib/wasm-host" }
land-wasm-server = { path = "lib/wasm-server" }
# third-party dependencies
anyhow = "1.0.86"
async-trait = "0.1.81"
axum = "0.7.5"
chrono = "0.4.38"
clap = { version = "4.5.16", features = ["derive", "env"] }
http = "1.1.0"
lazy_static = "1.5.0"
metrics = "0.23.0"
md5 = "0.7.0"
once_cell = "1.19.0"
rand = "0.8.5"
reqwest = { version = "0.12.5", default-features = false, features = [
    "stream",
    "rustls-tls",
    "json",
] }
rust-embed = { version = "8.5.0", features = [
    "include-exclude",
    "compression",
] }
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"
strum = { version = "0.26.3", features = ["derive"] }
time = { version = "0.3.36", features = ["local-offset"] }
tokio = { version = "1.39.3", features = ["full"] }
tower-http = { version = "0.5.2", features = [
    "timeout",
    "cors",
    "fs",
    "trace",
] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [
    "time",
    "local-time",
    "env-filter",
] }
uuid = { version = "1.10.0", features = ["v4"] }
walkdir = "2.5.0"
wasmtime = { version = "23.0.2", features = ["component-model", "async"] }
wasmtime-wasi = "23.0.2"
wasi-preview1-component-adapter-provider = "23.0.2"
wit-bindgen = "0.30.0"
wit-bindgen-core = "0.30.0"
wit-bindgen-rust = "0.30.0"
wit-component = "0.215.0"
