[workspace]
members = [
    "crates/dao",
    "crates/helpers",
    "crates/modules",
    "crates/sdk",
    "crates/sdk-macro",
    "crates/tplvars",
    "crates/wasm-gen",
    "crates/wasm-host",
    "land-cli",
    "land-server",
    "land-worker",
]
default-members = ["land-cli"]
resolver = "2"

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["fuxiaohei <fudong0797@gmail.com>"]

[workspace.dependencies]
# internal dependencies
land-dao = { path = "crates/dao" }
land-helpers = { path = "crates/helpers" }
land-modules = { path = "crates/modules" }
land-sdk-macro = { path = "crates/sdk-macro" }
land-tplvars = { path = "crates/tplvars" }
land-wasm-gen = { path = "crates/wasm-gen" }

# third-party dependencies
anyhow = "1.0.91"
async-trait = "0.1.83"
axum = "0.7.7"
bytes = "1.8.0"
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive", "env"] }
http = "1.1.0"
lazy_static = "1.5.0"
md5 = "0.7.0"
rand = "0.8.5"
reqwest = { version = "0.12.8", default-features = false, features = [
    "stream",
    "rustls-tls",
    "json",
] }
rust-embed = { version = "8.5.0", features = [
    "include-exclude",
    "compression",
] }
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
strum = { version = "0.26.3", features = ["derive"] }
time = { version = "0.3.36", features = ["local-offset"] }
tokio = { version = "1.41.0", features = ["full"] }
tower-http = { version = "0.6.1", features = [
    "timeout",
    "cors",
    "fs",
    "trace",
] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [
    "time",
    "local-time",
    "env-filter",
] }
uuid = { version = "1.11.0", features = [
    "v4",
    "fast-rng",
    "macro-diagnostics",
] }
walkdir = "2.5.0"
wasmtime = { version = "26.0.0", features = ["component-model", "async"] }
wasmtime-wasi = "26.0.0"
wasi-preview1-component-adapter-provider = "25.0.1"
wit-bindgen-core = "0.34.0"
wit-bindgen-rust = "0.34.0"
wit-bindgen = "0.34.0"
wit-component = "0.219.1"
