[package]
name = "land-cli"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
clap = { workspace = true }
deadpool = { workspace = true }
land-core = { workspace = true }
land-worker = { workspace = true }
once_cell = { workspace = true }
path-slash = "0.2.1"
reqwest = { workspace = true }
rust-embed = "6.8.1"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
land-worker = { workspace = true }

[workspace]
members = [
    "binary/center",
    "binary/edge",
    "binary/runtime",
    "crates/core",
    "crates/dao",
    "crates/sdk",
    "crates/sdk-macro",
    "crates/storage",
    "crates/worker",
    "tests/integration-test",
    "tests/rust-test",
]

[workspace.package]
version = "0.1.0-rc.4"
edition = "2021"
authors = ["fuxiaohei <fudong0797@gmail.com>"]

[workspace.dependencies]
land-worker = { path = "crates/worker", version = "0.1.0-rc.4" }
land-sdk-macro = { path = "crates/sdk-macro", version = "0.1.0-rc.4" }
land-sdk = { path = "crates/sdk", version = "0.1.0-rc.4" }
land-core = { path = "crates/core", version = "0.1.0-rc.4" }
land-dao = { path = "crates/dao", version = "0.1.0-rc.4" }
land-storage = { path = "crates/storage", version = "0.1.0-rc.4" }
anyhow = "1.0.75"
axum = { version = "0.6.20", features = ["headers", "ws"] }
clap = { version = "4.4.0", features = ["derive", "env"] }
tokio = { version = "1.32.0", features = ["full"] }
tracing = "0.1.37"
lazy_static = "1.4.0"
time = "0.3.28"
tracing-subscriber = { version = "0.3.17", features = [
    "time",
    "local-time",
    "env-filter",
] }
chrono = "0.4.26"
once_cell = "1.18.0"
http = "0.2.9"
wit-bindgen = "0.10.0"
async-trait = "0.1.73"
hyper = { version = "0.14.27", features = ["full"] }
uuid = { version = "1.4.1", features = ["v4"] }
wasmtime = { version = "12.0.1", features = ["component-model", "async"] }
wasmtime-wasi = "12.0.1"
wit-bindgen-core = "0.10.0"
wit-bindgen-rust = "0.10.0"
wit-component = "0.14.0"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
reqwest = { version = "0.11.20", default-features = false, features = [
    "stream",
    "rustls-tls",
    "blocking",
    "json",
    "multipart",
] }
envconfig = "0.10.0"
futures-util = "0.3.28"
rand = "0.8.5"
deadpool = { version = "0.9.5", features = ["rt_tokio_1"] }
opendal = { version = "0.39.0", default-features = false, features = [
    "services-fs",
    "services-redis",
    "services-s3",
    "services-memory",
    "rustls",
] }
strum = { version = "0.25.0", features = ["derive"] }
