[package]
name = "moni-serverless"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[workspace]
members = [
    "examples/rust-basic",
    "examples/rust-fetch",
    "examples/rust-kv",
    "examples/rust-router",
    "moni-cli",
    "moni-core",
    "moni-runtime",
    "moni-sdk",
    "moni-sdk/macro",
]

[workspace.package]
version = "0.1.2"
edition = "2021"
authors = ["fuxiaohei <fudong0797@gmail.com>"]

[dependencies]
clap = { workspace = true }
moni-core = { path = "moni-core" }
moni-runtime = { path = "moni-runtime" }
tokio = { workspace = true }

[build-dependencies]
moni-runtime = { path = "moni-runtime" }

[workspace.dependencies]
reqwest = "0.11.14"
clap = { version = "4.1.8", features = ["derive"] }
tokio = { version = "1.26.0", features = ["full"] }
serde = { version = "1.0.154", features = ["derive"] }
anyhow = "1.0.69"
bytes = "1.4.0"
http = "0.2.9"
bincode = "1.3.3"
toml = "0.7.2"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = [
    "time",
    "local-time",
    "env-filter"
] }
time = "0.3.20"
lazy_static = "1.4.0"
wit-bindgen-core = { git = "https://github.com/bytecodealliance/wit-bindgen" }
wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen" }
wit-component = "0.7.3"
wit-parser = "0.6.4"
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime", rev = "8d3a881b524d56498dfc71b65818b2abbeb1da44", features = [
    "component-model",
    "async"
] }
wasi-host = { git = "https://github.com/bytecodealliance/preview2-prototyping", package = "host" }
wasi-cap-std-sync = { git = "https://github.com/bytecodealliance/preview2-prototyping" }
deadpool = { version = "0.9.5", features = ["rt_tokio_1"] }
async-trait = "0.1.66"
once_cell = "1.17.1"
hyper = { version = "0.14.24", features = ["full"] }
actix-web = "4.3.1"
