[workspace]
members = [
    "crates/common",
    "crates/core",
    "crates/dao",
    "land-cli",
    "land-server",
    "land-worker",
]
default-members = ["land-cli"]
resolver = "2"

[workspace.package]
version = "0.3.0"
edition = "2021"
authors = ["fuxiaohei <fudong0797@gmail.com>"]

[workspace.dependencies]
land-common = { path = "./crates/common" }
land-core = { path = "./crates/core" }
land-dao = { path = "./crates/dao" }
lazy_static = "1.4.0"
time = { version = "0.3.34", features = ["local-offset"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [
    "time",
    "local-time",
    "env-filter",
] }
clap = { version = "4.5.4", features = ["derive", "env"] }
tokio = { version = "1.37.0", features = ["full"] }
anyhow = "1.0.81"
once_cell = "1.19.0"
axum = "0.7.5"
rust-embed = { version = "8.3.0", features = [
    "include-exclude",
    "compression",
] }
tower-http = { version = "0.5.2", features = [
    "timeout",
    "cors",
    "fs",
    "trace",
] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
async-trait = "0.1.79"
chrono = "0.4.37"
reqwest = { version = "0.12.2", default-features = false, features = [
    "stream",
    "rustls-tls",
    "json",
] }
base64 = "0.22.0"
rand = "0.8.5"
uuid = { version = "1.8.0", features = ["v4"] }
http = "1.1.0"
