[package]
name = "land-cli"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[build-dependencies]
land-worker = { workspace = true }

[workspace]
members = [
    "binary/center",
    "binary/edge",
    "binary/runtime",
    "crates/worker",
    "crates/sdk-macro",
    "crates/sdk",
    "crates/core",
    "crates/dao",
    "crates/storage",
    "tests/rust-test"
]

[workspace.package]
version = "0.1.0-b4"
edition = "2021"
authors = ["fuxiaohei <fudong0797@gmail.com>"]

[workspace.dependencies]
land-worker = { path = "crates/worker", version = "0.1.0-b4" }
land-sdk-macro = { path = "crates/sdk-macro", version = "0.1.0-b4" }
land-sdk = { path = "crates/sdk", version = "0.1.0-b4" }
land-core = { path = "crates/core", version = "0.1.0-b4" }
land-dao = { path = "crates/dao", version = "0.1.0-b4" }
land-storage = { path = "crates/storage", version = "0.1.0-b4" }
anyhow = "1.0.72"
axum = "0.6.19"
clap = { version = "4.3.12", features = ["derive", "env"] }
tokio = { version = "1.29.1", features = ["full"] }
tracing = "0.1.37"
lazy_static = "1.4.0"
time = "0.3.23"
tracing-subscriber = { version = "0.3.17", features = [
    "time",
    "local-time",
    "env-filter"
] }
chrono = "0.4.26"
once_cell = "1.18.0"
http = "0.2.9"
wit-bindgen = "0.9.0"
async-trait = "0.1.71"
hyper = { version = "0.14.27", features = ["full"] }
uuid = { version = "1.4.1", features = ["v4"] }
wasmtime = { version = "10.0.1", features = ["component-model", "async"] }
wasmtime-wasi = "10.0.1"
wit-bindgen-core = "0.9.0"
wit-bindgen-rust = "0.9.0"
serde = { version = "1.0.171", features = ["derive"] }
