[package]
name = "rtland-engine"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
axum-extra = { version = "0.9.4", features = ["cookie"] }
axum-htmx = "0.6.0"
axum-template = { version = "2.4.0", features = ["handlebars"] }
chrono = { workspace = true }
clap = { workspace = true }
color-print = "0.3.6"
gravatar = "0.2.0"
handlebars = "6.1.0"
hostname = "0.4.0"
land-dao = { workspace = true }
land-utils =  { workspace = true }
land-wasm-host = { workspace = true }
lazy_static = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = { version = "0.15.3", default-features = false, features = [
    "http-listener",
] }
minify-html = "0.15.0"
once_cell = { workspace = true }
rand = { workspace = true }
rust-embed = { version = "8.5.0", features = [
    "include-exclude",
    "compression",
] }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = "2.5.2"
walkdir = "2.5.0"
xid = "1.1.1"

[build-dependencies]
vergen-git2 = { version = "1.0.0", features = ["build", "cargo", "rustc"] }

[workspace]
members = [
    "crates/dao",
    "crates/sdk",
    "crates/sdk-macro", "crates/utils",
    "crates/wasm-gen",
    "crates/wasm-host",
    "tests/hello-wasm",
]

[workspace.package]
version = "0.1.5"
edition = "2021"
authors = ["fuxiaohei <fudong0797@gmail.com>"]

[workspace.dependencies]
# internal dependencies
land-dao = { path = "crates/dao" }
land-sdk = { path = "crates/sdk" }
land-sdk-macro = { path = "crates/sdk-macro" }
land-wasm-gen = { path = "crates/wasm-gen" }
land-wasm-host = { path = "crates/wasm-host" }
land-utils = { path = "crates/utils" }

# third-party dependencies
anyhow = "1.0.89"
axum = "0.7.7"
async-trait = "0.1.83"
chrono = "0.4.38"
clap = { version = "4.5.19", features = ["derive", "env"] }
http = "1.1.0"
lazy_static = "1.5.0"
metrics = "0.23.0"
once_cell = "1.20.2"
rand = "0.8.5"
reqwest = { version = "0.12.8", default-features = false, features = [
    "stream",
    "rustls-tls",
    "json",
] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"
strum = { version = "0.26.3", features = ["derive"] }
time = { version = "0.3.36", features = ["local-offset"] }
tokio = { version = "1.40.0", features = ["full"] }
tower-http = { version = "0.6.1", features = [
    "timeout",
    "cors",
    "fs",
    "trace",
] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [
    "time",
    "local-time",
    "env-filter",
] }
wit-bindgen = "0.33.0"
