[package]
name = "moni-serverless"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
clap = { workspace = true }
moni-lib = { path = "./moni-lib" }
moni-rpc = { path = "./moni-lib/rpc" }
serde = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
moni-runtime = { path = "moni-runtime" }

[workspace]
members = [
    "examples/rust-basic",
    "examples/rust-fetch",
    "examples/rust-router",
    "moni-cli",
    "moni-lib",
    "moni-lib/rpc",
    "moni-runtime",
    "moni-sdk",
    "moni-sdk/macro",
]

[workspace.dependencies]
anyhow = "1.0.70"
async-trait = "0.1.68"
axum = "0.6.16"
clap = { version = "4.2.4", features = ["derive"] }
chrono = "0.4.24"
http = "0.2.9"
hyper = { version = "0.14.26", features = ["full"] }
lazy_static = "1.4.0"
once_cell = "1.17.1"
reqwest = { version = "0.11.16", features = ["stream"] }
serde = { version = "1.0.160", features = ["derive"] }
time = "0.3.20"
tokio = { version = "1.27.0", features = ["full"] }
toml = "0.7.3"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = [
    "time",
    "local-time",
    "env-filter"
] }
wasi-cap-std-sync = { git = "https://github.com/bytecodealliance/preview2-prototyping" }
wasi-host = { git = "https://github.com/bytecodealliance/preview2-prototyping", package = "host" }
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime", rev = "299131ae2d6655c49138bfab2c4469650763ef3b", features = [
    "component-model",
    "async"
] }
wit-bindgen = "0.5.0"
wit-bindgen-core = "0.5.0"
wit-bindgen-rust = "0.5.0"
wit-component = "0.8.1"

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["fuxiaohei <fudong0797@gmail.com>"]
