[package]
name = "rtland-engine"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
color-print = "0.3.6"
time = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[build-dependencies]
vergen-git2 = { version = "1.0.0", features = ["build", "cargo", "rustc"] }

[workspace]
members = ["crates/wasm-gen", "crates/wasm-host"]

[workspace.package]
version = "0.1.5"
edition = "2021"
authors = ["fuxiaohei <fudong0797@gmail.com>"]

[workspace.dependencies]
# internal dependencies
land-wasm-gen = { path = "crates/wasm-gen" }

# third-party dependencies
anyhow = "1.0.89"
clap = { version = "4.5.19", features = ["derive", "env"] }
time = { version = "0.3.36", features = ["local-offset"] }
tokio = { version = "1.40.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [
    "time",
    "local-time",
    "env-filter",
] }
