[package]
name = "land-cli"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
clap = { workspace = true }
deadpool = { workspace = true }
land-core = { workspace = true }
land-worker = { workspace = true }
once_cell = { workspace = true }
reqwest = { workspace = true }
rust-embed = "6.8.1"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
land-worker = { workspace = true }

[workspace]
members = [
    "binary/center",
    "binary/edge",
    "binary/runtime",
    "crates/core",
    "crates/dao",
    "crates/sdk",
    "crates/sdk-macro",
    "crates/storage",
    "crates/worker",
    "tests/rust-test",
]

[workspace.package]
version = "0.1.0-b9"
edition = "2021"
authors = ["fuxiaohei <fudong0797@gmail.com>"]

[workspace.dependencies]
land-worker = { path = "crates/worker", version = "0.1.0-b9" }
land-sdk-macro = { path = "crates/sdk-macro", version = "0.1.0-b9" }
land-sdk = { path = "crates/sdk", version = "0.1.0-b9" }
land-core = { path = "crates/core", version = "0.1.0-b9" }
land-dao = { path = "crates/dao", version = "0.1.0-b9" }
land-storage = { path = "crates/storage", version = "0.1.0-b9" }
anyhow = "1.0.72"
axum = { version = "0.6.19", features = ["headers", "ws"] }
clap = { version = "4.3.19", features = ["derive", "env"] }
tokio = { version = "1.29.1", features = ["full"] }
tracing = "0.1.37"
lazy_static = "1.4.0"
time = "0.3.24"
tracing-subscriber = { version = "0.3.17", features = [
    "time",
    "local-time",
    "env-filter",
] }
chrono = "0.4.26"
once_cell = "1.18.0"
http = "0.2.9"
wit-bindgen = "0.9.0"
async-trait = "0.1.72"
hyper = { version = "0.14.27", features = ["full"] }
uuid = { version = "1.4.1", features = ["v4"] }
wasmtime = { git = "https://github.com/bytecodealliance/wasmtime", tag = "dev", features = [
    "component-model",
    "async",
] }
wasmtime-wasi = { git = "https://github.com/bytecodealliance/wasmtime", tag = "dev" }
wit-bindgen-core = "0.9.0"
wit-bindgen-rust = "0.9.0"
serde = { version = "1.0.179", features = ["derive"] }
serde_json = "1.0.104"
reqwest = { version = "0.11.18", default-features = false, features = [
    "stream",
    "rustls-tls",
    "blocking",
    "json",
    "multipart",
] }
envconfig = "0.10.0"
futures-util = "0.3.28"
rand = "0.8.5"
deadpool = { version = "0.9.5", features = ["rt_tokio_1"] }
