[package]
name = "moni-serverless"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]

[workspace]
members = ["moni-cli", "moni-lib"]

[workspace.dependencies]
lazy_static = "1.4.0"
time = "0.3.20"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = [
    "time",
    "local-time",
    "env-filter"
] }
clap = { version = "4.2.1", features = ["derive"] }
tokio = { version = "1.27.0", features = ["full"] }

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["fuxiaohei <fudong0797@gmail.com>"]
