[package]
name = "moni-serverless"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
wit-component = "0.7.4"

[build-dependencies]
moni-runtime = { path = "moni-runtime" }

[workspace]
members = [
    "examples/rust-basic",
    "examples/rust-fetch",
    "examples/rust-router",
    "moni-cli",
    "moni-lib",
    "moni-runtime",
    "moni-sdk",
    "moni-sdk/macro"
]

[workspace.dependencies]
anyhow = "1.0.70"
async-trait = "0.1.68"
axum = "0.6.12"
clap = { version = "4.2.1", features = ["derive"] }
http = "0.2.9"
hyper = { version = "0.14.25", features = ["full"] }
lazy_static = "1.4.0"
once_cell = "1.17.1"
reqwest = { version = "0.11.16", features = ["stream"] }
serde = { version = "1.0.160", features = ["derive"] }
time = "0.3.20"
tokio = { version = "1.27.0", features = ["full"] }
toml = "0.7.3"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = [
    "time",
    "local-time",
    "env-filter"
] }
wasi-cap-std-sync = { git = "https://github.com/bytecodealliance/preview2-prototyping" }
wasi-host = { git = "https://github.com/bytecodealliance/preview2-prototyping", package = "host" }
wasmtime = { version = "7.0.0", features = ["component-model", "async"] }
wit-bindgen = "0.4.0"
wit-bindgen-core = "0.4.0"
wit-bindgen-rust = "0.4.0"
wit-parser = "0.6.4"
wit-component = "0.7.4"

[workspace.package]
version = "0.2.0"
edition = "2021"
authors = ["fuxiaohei <fudong0797@gmail.com>"]
