[package]
name = "moni-serverless"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[workspace]
members = [
    "moni-cli",
    "moni-core",
    "moni-runtime",
    "moni-sdk",
    "moni-sdk/macro",
    "examples/rust-basic",
]

[workspace.package]
version = "0.1.1"
edition = "2021"
authors = ["fuxiaohei <fudong0797@gmail.com>"]

[dependencies]
clap = { workspace = true }
tokio = { workspace = true }

[build-dependencies]
moni-runtime = { path = "moni-runtime" }

[workspace.dependencies]
clap = { version = "4.1.8", features = ["derive"] }
tokio = { version = "1.26.0", features = ["full"] }
serde = { version = "1.0.152", features = ["derive"] }
anyhow = "1.0.69"
bytes = "1.4.0"
http = "0.2.9"
bincode = "1.3.3"
toml = "0.7.2"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = [
    "time",
    "local-time",
    "env-filter"
] }
time = "0.3.20"
lazy_static = "1.4.0"
wit-bindgen-core = { git = "https://github.com/bytecodealliance/wit-bindgen" }
wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen" }
wit-component = "0.7.1"
wit-parser = "0.6.2"
wasmtime = { version = "6.0.0", features = ["component-model", "async"] }
wasi-host = { git = "https://github.com/bytecodealliance/preview2-prototyping", package = "host" }
wasi-cap-std-sync = { git = "https://github.com/bytecodealliance/preview2-prototyping" }
