[package]
name = "moni-rpc"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
prost = "0.11.9"
tonic = "0.9.2"
tracing = { workspace = true }
moni-lib = { path = "../../moni-lib" }

[build-dependencies]
tonic-build = "0.9.2"
