[package]
name = "moni-rpc"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
gravatar = "0.2.0"
http = { workspace = true }
moni-lib = { path = "../../moni-lib" }
prost = "0.11.9"
rand = { workspace = true }
tonic = "0.9.2"
tonic-web = "0.9.2"
tower-http = "0.4.0"
tracing = { workspace = true }

[build-dependencies]
tonic-build = "0.9.2"

[lib]
doctest = false
