version: "3"

networks:
  runtime_land_center_network:
    external: true

services:
  proxy:
    image: traefik:3.0
    command: --api.insecure=true --providers.docker=true --providers.docker.exposedByDefault=false
    ports:
      - "80:80"
    networks:
      - runtime_land_center_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  runtimeland-center:
    image: ghcr.io/fuxiaohei/runtime-land-center:v0.1.0-b16
    restart: always
    environment:
      - DB_HOST=${MYSQL_HOST}
      - DB_PORT=${MYSQL_PORT}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_DATABASE=${MYSQL_DATABASE}
      - HTTP_ADDR=0.0.0.0:7899
      - STORAGE_TYPE=${STORAGE_TYPE}
      - S3_ENDPOINT=${S3_ENDPOINT}
      - S3_BUCKET=${S3_BUCKET}
      - S3_ACCESS_KEY_ID=${S3_ACCESS_KEY_ID}
      - S3_SECRET_ACCESS_KEY=${S3_SECRET_ACCESS_KEY}
      - S3_ROOT_PATH=${S3_ROOT_PATH}
    networks:
      - runtime_land_center_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.land-runtime.rule=Host(`${CENTER_HOST}`)
  runtimeland-dashboard:
    image: ghcr.io/fuxiaohei/runtime-land-dashboard:v0.1.0-b16
    restart: always
    networks:
      - runtime_land_center_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.land-web.rule=Host(`${DASHBOARD_HOST}`)
