manifest = "v1"
name = "rust-router"
template_name = "HTTP Router"
project = "rust-router-example"
description = "serve different routes with different handlers"
authors = []
language = "rust"

[build]
rust_target_dir = "../../target"