[package]
name = "land-sdk-macro"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
description = "Database migration for Runtime Land"
license = "Apache-2.0"
documentation = "https://runtime.land"
categories = ["wasm"]
keywords = ["webassembly", "wasm", "serverless"]
repository = "https://github.com/fuxiaohei/runtime.land"

[dependencies]
anyhow = { workspace = true }
http = { workspace = true }
quote = "1.0.28"
syn = { version = "2.0.18", features = ["full"] }

[lib]
proc-macro = true
test = false
doctest = false
