[package]
name = "lol-sdk-macro"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = { workspace = true }
http = { workspace = true }
quote = "1.0.28"
syn = { version = "2.0.18", features = ["full"] }

[lib]
proc-macro = true
test = false
doctest = false
