[package]
name = "land-dao"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = { workspace = true }
async-std = { version = "1.12.0", features = ["attributes", "tokio1"] }
bcrypt = "0.15.0"
chrono = { workspace = true }
clap = { workspace = true }
gravatar = "0.2.0"
once_cell = { workspace = true }
rand = { workspace = true }
random_word = { version = "0.4.1", features = ["en"] }
sea-orm = { version = "0.12.1", features = [
    "sqlx-mysql",
    "runtime-tokio-rustls",
] }
sea-orm-migration = { version = "0.12.1" }
strum = { version = "0.25.0", features = ["derive"] }
tracing = { workspace = true }
uuid = { workspace = true }
