[package]
name = "land-dao"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = "1.0.71"
async-std = { version = "1", features = ["attributes", "tokio1"] }
bcrypt = "0.15.0"
chrono = "0.4.26"
clap = { version = "4.3.8", features = ["derive", "env"] }
gravatar = "0.2.0"
once_cell = "1.18.0"
rand = "0.8.5"
sea-orm = { version = "0.11.3", features = [
    "sqlx-mysql",
    "runtime-tokio-rustls"
] }
sea-orm-migration = { version = "0.11.3" }
strum = { version = "0.25.0", features = ["derive"] }
tracing = "0.1.37"
uuid = { version = "1.4.0", features = ["v4"] }
