[package]
name = "land-dao"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.8", features = ["derive", "env"] }
once_cell = "1.18.0"
sea-orm = { version = "0.11.3", features = [
    "sqlx-mysql",
    "runtime-tokio-rustls"
] }
tracing = "0.1.37"
