[package]
name = "land-sdk"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
description = "land sdk API"
license = "Apache-2.0"

[dependencies]
anyhow = { workspace = true }
http = { workspace = true }
land-sdk-macro = { workspace = true }
lazy_static = { workspace = true }
matchit = "0.7.3"
wit-bindgen = { workspace = true }

[lib]
doctest = false
