[package]
name = "land-sdk"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
documenation = { workspace = true }
categories = { workspace = true }
keywords = { workspace = true }
repository = { workspace = true }

[dependencies]
anyhow = { workspace = true }
http = { workspace = true }
land-sdk-macro = { path = "./macro" }
lazy_static = { workspace = true }
matchit = "0.7.0"
wit-bindgen = { workspace = true }

[lib]
doctest = false
