[package]
name = "land-worker-server"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
hostname = { workspace = true }
land-wasm = { workspace = true }
metrics = "0.22.3"
metrics-exporter-prometheus = { version = "0.14.0", default-features = false, features = [
    "http-listener",
] }
once_cell = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
xid = "1.0.3"
