networks:
  runtime_land_network:
    external: true

services:
  proxy:
    platform: linux/amd64
    image: traefik:v3.0
    container_name: "runtime-land-dev-traefik-proxy"
    command:
      - "--api=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--providers.file.directory=/data/runtime-land/traefik/"
      - "--providers.file.watch=true"
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.filepath=/data/runtime-land/logs/access.log"
      - "--accesslog.fields.headers.defaultmode=keep"
      - "--accesslog.fields.headers.names.Authorization=drop"
    restart: always
    ports:
      - "80:80"
    networks:
      - runtime_land_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${LAND_DATA_DIR}:/data/runtime-land
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik-dashboard-http-router.entrypoints=http
      - traefik.http.routers.traefik-dashboard-http-router.rule=Host(`${TRAEFIK_DOMAIN}`)
      - traefik.http.routers.traefik-dashboard-http-router.service=api@internal
      - traefik.http.middlewares.dashboard_auth.basicauth.users=admin:$$apr1$$TZ3Indax$$xAOly0K/dH13PEfXHNqvS1
      - traefik.http.routers.traefik-dashboard-http-router.middlewares=dashboard_auth
  worker:
    platform: linux/amd64
    image: ghcr.io/fuxiaohei/runtime-land-worker:dev
    container_name: "runtime-land-dev-worker"
    restart: always
    environment:
      - LAND_SERVER_TOKEN=${LAND_SERVER_TOKEN}
      - LAND_SERVICE_NAME=land-worker@docker
      - LAND_DATA_DIR=/data/runtime-land
      - LAND_SERVER_URL=${LAND_SERVER_URL}
      - HOSTNAME=${HOSTNAME}
    ports:
      - "9000:9000" # metrics port
    networks:
      - runtime_land_network
    volumes:
      - ${LAND_DATA_DIR}:/data/runtime-land
    labels:
      - traefik.enable=true
      - traefik.http.services.land-worker.loadbalancer.server.port=9844
