global:
  scrape_interval: "1m"
  scrape_timeout: "10s"
  evaluation_interval: "1m"
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
scrape_configs:
  - job_name: "runtime-land-dev"
    static_configs:
      - targets:
          - "127.0.0.1:9000"
