[package]
name = "rust-basic"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.70"
http = "0.2.9"
land-sdk = { path = "../../crates/sdk" }
wit-bindgen = "0.7.0"

[lib]
crate-type = ["cdylib"]
