[package]
name = "land-service"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = { workspace = true }
rust-embed = { workspace = true }
serde = { workspace = true }
toml = "0.8.19"
tracing = { workspace = true }
