[package]
name = "land-service"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = { workspace = true }
clerk-rs = "0.3.0"
jsonwebtoken = "9.3.0"
land-dao = { workspace = true }
once_cell = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json =  { workspace = true }
tracing = { workspace = true }
