[package]
name = "land-center"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
clap = { workspace = true }
land-core = { workspace = true }
land-dao = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tower-http = { version = "0.4.3", features = ["cors"] }
tracing = { workspace = true }
validator = { version = "0.16.1", features = ["derive"] }
