[package]
name = "land-sdk-macro"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
description = "Land SDK macro provides a procedural macro to generate Land SDK code."
license = "Apache-2.0"

[dependencies]
anyhow = { workspace = true }
http = { workspace = true }
quote = "1.0.33"
syn = { version = "2.0.38", features = ["full"] }

[lib]
proc-macro = true
test = false
doctest = false
