[package]
name = "land-core"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
lazy_static = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[build-dependencies]
vergen = { version = "8.2.4", features = ["build", "cargo"] }
