[package]
name = "land-tplvars"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
land-dao = { workspace = true }
land-utils = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
