[package]
name = "land-server"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }
description = "A tiny serverless platform for WebAssembly"
license = "Apache-2.0"
documentation = "https://runtime.land"
categories = ["wasm"]
keywords = ["webassembly", "wasm", "serverless"]
repository = "https://github.com/fuxiaohei/runtime.land"
readme = "README.md"
homepage = "https://runtime.land"

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
clap = { workspace = true }
land-core = { workspace = true }
land-restful = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }