version: "3"

networks:
  runtime_land_center_network:
    external: true

services:
  mysql-db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${MYSQL_DIR}:/var/lib/mysql
    networks:
      - runtime_land_center_network
  redis:
    image: redis:7.2
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ${REDIS_DIR}:/data
    networks:
      - runtime_land_center_network
  traefik-proxy:
    image: traefik:3.0
    command: --api.insecure=true --providers.docker=true --providers.docker.exposedByDefault=false
    ports:
      - "80:80"
      - "8080:8080"
    networks:
      - runtime_land_center_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DASHBOARD_HOST}`)"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
  runtimeland-center:
    image: docker.io/library/land-center:latest
    restart: always
    environment:
      - DB_HOST=${CENTER_MYSQL_HOST}
      - DB_PORT=${CENTER_MYSQL_PORT}
      - DB_USER=${CENTER_MYSQL_USER}
      - DB_PASSWORD=${CENTER_MYSQL_PASSWORD}
      - DB_DATABASE=${CENTER_MYSQL_DATABASE}
      - HTTP_ADDR=${CENTER_HTTP_ADDR}
      - STORAGE_TYPE=${CENTER_STORAGE_TYPE}
      - FS_PATH=/data
      - REGION_TOKEN=${CENTER_REGION_TOKEN}
    volumes:
      - ${CENTER_FS_PATH}:/data
    networks:
      - runtime_land_center_network
    depends_on:
      - mysql-db
    labels:
      - traefik.enable=true
      - traefik.http.routers.land-runtime.rule=Host(`${CENTER_TRAEFIK_HOST}`)
  runtimeland-edge:
    image: docker.io/library/land-edge:latest
    restart: always
    environment:
      - HTTP_ADDR=${EDGE_HTTP_ADDR}
      - REMOTE_STORE_ENABLED=${EDGE_REMOTE_STORE_ENABLED}
      - CENTER_ADDR=${EDGE_CENTER_ADDR}
      - CENTER_TOKEN=${EDGE_CENTER_TOKEN}
      - CENTER_PROTOCOL=${EDGE_CENTER_PROTOCOL}
      - TRAEFIK_REDIS_ADDR=${EDGE_TRAEFIK_REDIS_ADDR}
      - TRAEFIK_REDIS_PASSWORD=${EDGE_TRAEFIK_REDIS_PASSWORD}
      - TRAEFIK_REDIS_DB=${EDGE_TRAEFIK_REDIS_DB}
      - TRAEFIK_RUNTIME_NAME=${EDGE_TRAEFIK_RUNTIME_NAME}
      - FS_PATH=/data
    volumes:
      - ${EDGE_FS_PATH}:/data
    networks:
      - runtime_land_center_network
    depends_on:
      - runtimeland-center
      - redis
  runtimeland-runtime:
    image: docker.io/library/land-runtime:latest
    restart: always
    environment:
      - FS_PATH=/data
      - HTTP_ADDR=${RUMTIME_HTTP_ADDR}
      - EDGE_ADDR=${RUNTIME_EDGE_ADDR}
      - EDGE_SYNC_ENABLED=${RUMTIME_EDGE_SYNC_ENABLED}
      - EDGE_SYNC_INTERVAL=${RUNTIME_EDGE_SYNC_INTERVAL}
    networks:
      - runtime_land_center_network
    volumes:
      - ${RUNTIME_FS_PATH}:/data
    labels:
      - traefik.enable=true
    depends_on:
      - runtimeland-edge
    deploy:
      replicas: 2
