version: '3'

networks:
  land_serverless_network:
    external: true

services:
  redis:
    image: redis:7.0
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - ${REDIS_DIR}:/data
    networks:
      - land_serverless_network
  proxy:
    image: traefik:v2.10
    command: --api.insecure=true --providers.redis.endpoints=redis:6379 --providers.redis.password=${REDIS_PASSWORD} --providers.docker=true --providers.docker.exposedByDefault=false
    ports:
      - "80:80"
      - "8080:8080" # traefik dashboard
    networks:
      - land_serverless_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_INIT_SQL}:/docker-entrypoint-initdb.d/init.sql
    networks:
      - land_serverless_network
