[package]
name = "moni-cli"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
clap = { workspace = true }
moni-lib = { path = "../moni-lib" }
tokio = { workspace = true }
tracing = { workspace = true }
