[package]
name = "moni-cli"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
clap = { workspace = true }
moni-core = { path = "../moni-core" }
serde = { workspace = true }
tokio = { workspace = true }
