[package]
name = "moni-cli"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = { workspace = true }
axum = { workspace = true }
bincode = { workspace = true }
clap = { workspace = true }
hyper = { workspace = true }
moni-core = { path = "../moni-core" }
moni-runtime = { path = "../moni-runtime" }
once_cell = { workspace = true }
rust-embed = "6.6.0"
serde = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
