[package]
name = "moni-sdk"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

[dependencies]
anyhow = { workspace = true }
http = { workspace = true }
moni-sdk-macro = { path = "./macro" }
wit-bindgen = { workspace = true }
