# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build
on:
  push:
    branches:
      - main
    tags: ["v*"]
env:
  CARGO_TERM_COLOR: always
jobs:
  build_all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "build-all"
      - name: Update local toolchain
        run: |
          rustup update stable
          rustup component add clippy
          rustup target add wasm32-wasi
          cargo install wizer --all-features
      - name: Install protobuf
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler libprotobuf-dev
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
          wizer --version
          protoc --version
      - name: Run unit tests
        run: |
          cargo test --all --release
      - name: Build all
        run: |
          cargo build --release -p land-server
          cargo build --release -p land-cli
          cargo build --release -p land-runtime
      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: land-binary
          path: |
            target/release/land-cli
            target/release/land-server
            target/release/land-runtime

  test-wit-v2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "test-wit-v2"
      - name: Update local toolchain
        run: |
          rustup update stable
          rustup target add wasm32-wasi
      - name: Install protobuf
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler libprotobuf-dev
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
          protoc --version
      - name: Run test-wit-v2
        run: |
          make test-wit-v2
