name: Dockerize

on:
  push:
    branches:
      - main
    tags: ["v*"]
env:
  CARGO_TERM_COLOR: always
concurrency:
  group: dockerize-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dockerize:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./deploy/lol-server.Dockerfile
            image: ghcr.io/${{ github.repository_owner }}/lol-server
          - dockerfile: ./deploy/lol-runtime.Dockerfile
            image: ghcr.io/${{ github.repository_owner }}/lol-runtime
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "lol-image"
      - name: Update local toolchain
        run: |
          rustup update stable
      - name: Install protobuf
        run: |
          sudo apt update
          sudo apt install -y protobuf-compiler libprotobuf-dev
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          protoc --version
      - name: Build all
        run: |
          cargo build --release
          cargo build --release -p lol-runtime
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable=true
            type=sha,enable=true,format=short
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Container Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
  webpage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./deploy/lol-web.Dockerfile
            image: ghcr.io/${{ github.repository_owner }}/lol-web
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ matrix.image }}
          tags: |
            type=raw,value=latest,enable=true
            type=sha,enable=true,format=short
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Github Container Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
