name: Run Tests
on:
  push:
    branches:
      - main
      - dev
    tags: ["v*"]
env:
  CARGO_TERM_COLOR: always

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update local toolchain
        run: |
          rustup update stable
          rustup component add rustfmt
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "tests"
      - name : Install dependencies
        run: |
          bash ./scripts/land-server-deps.sh
          mkdir -p /opt/bin
          cp -R wizer-v6.0.0-x86_64-linux /opt/bin/wizer
      - name: Build binaries
        run: |
          cargo build -p land-cli --release
      - name: Test js-files
        run: |
          bash ./tests/test-js-files.sh
     