name: Run Tests
on:
  push:
    branches:
      - main
      - dev
    tags: ["v*"]
env:
  CARGO_TERM_COLOR: always
concurrency:
  group: run-tests-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-wasm-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update local toolchain
        run: |
          rustup update stable
          rustup component add rustfmt
          rustup target add wasm32-wasi
      - name: Install wasm-opt
        run: |
          sudo apt install -y binaryen xz-utils
          bash ./scripts/land-server-deps.sh
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "build"
      - name: test hello-wasm
        run: |
          bash ./tests/test_examples.sh