name: Unit Tests
on:
  push:
    branches:
      - main
    tags: ["v*"]
env:
  CARGO_TERM_COLOR: always
concurrency:
  group: unittest-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update local toolchain
        run: |
          rustup update stable
          rustup component add rustfmt
          rustup target add wasm32-wasi
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "unittest"
      - name: Install wasm-tools
        run: cargo install wasm-tools
      - name: Build testing wasm
        run: ./tests/build_tests_wasm.sh
      - name: Run Tests
        run: cargo test --workspace --release
      - name: Build cli, runtime and integration-test
        run: |
          cargo build --release -p land-cli
          cargo build --release -p land-runtime
          cargo build --release -p integration-test
      - name: Upload cli, runtime and integration-test
        uses: actions/upload-artifact@v3
        with:
          name: integration-test
          path: |
            target/release/land-cli
            target/release/land-runtime
            target/release/integration-test
            deploy/download-deps-binary.sh
  integration-test:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Update local toolchain
        run: |
          rustup update stable
          rustup component add rustfmt
          rustup target add wasm32-wasi
      - name: Download cli, runtime and integration-test
        uses: actions/download-artifact@v3
        with:
          name: integration-test
      - name: Run integration-test
        run: |
          chmod +x ./download-deps-binary.sh
          ./download-deps-binary.sh
          chmod +x ./integration-test
          chmod +x ./land-cli
          chmod +x ./land-runtime
          ./integration-test
        env:
          SDK_VERSION: '{ git = "https://github.com/fuxiaohei/runtime-land" }'
