name: Unit Tests
on:
  push:
    branches:
      - main
    tags: ["v*"]
env:
  CARGO_TERM_COLOR: always
concurrency:
  group: unittest-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update local toolchain
        run: |
          rustup update stable
          rustup component add rustfmt
          rustup target add wasm32-wasi
          cargo install wasm-tools
      - name: Build testing wasm
        run: ./tests/build_tests_wasm.sh
      - name: Run Tests
        run: cargo test --workspace --release